### ISSUE TITLE
find a replacement / fork tokamak

### ISSUE THREAD

**Issue by qmx** [caelum/restfulie#67]
Tokamak's project isn't looking forward to improve its DSL (I think they don't need it), and I think that end users can use those features too. (I certainly would)

Another showstopper is that guilherme made 12 pull requests, that took almost a month to get integrated. Restfulie release cycle should be self-contained.

So I propose forking or finding an alternative that can evolve together.

**Comment by andersonleite** [comment]
I couldn't understand why not to accept the last refactoring pull request too. I propose to fork it as qmx suggested.

**Comment by guilhermesilveira** [comment]
Some of our users don't get the features or responses timely, and that might kill and open source attempt. That is the biggest issue, then evolving the internal design would also be good.

**Comment by lfcipriani** [comment]
Yes, we believe that the DSL doesn't need to improved for now. We evolve the library when we have strong evidences and applied use cases in our production systems that give concrete meaning to a change, since we had some problems previously caused by volatile code, APIs, DSLs, evil ifs.

We are implementing community-driven, reliable, production-ready, experimented, legible version of abril/tokamak. If even with all our concerns and experience we are not fulfilling the needs of the community we suggest you to fork the project, that's not a problem, it's the solution. We did this internally with some projects.

**Comment by abstractj** [comment]
Fork +1

thanks lfcipriani for your comprehension, now restfulie is totally free :D

**Comment by guilhermesilveira** [comment]
github.com/caelum/hypertemplate
