### ISSUE TITLE
Old references to tokamak instead of hypertemplate

### ISSUE THREAD

**Issue by hemju** [caelum/restfulie#74]
https://github.com/caelum/restfulie/wiki/ruby_tokamak
https://github.com/caelum/restfulie/wiki
...

Since the new version now uses hypertemplate, I think the wiki should be updated as well.

**Comment by guilhermesilveira** [comment]
Sure. Can you help us updating it?

Guilherme Silveira

On 01/06/2011 12:50 PM, "hjuskewycz" <
reply@reply.github.com>
wrote:

https://github.com/caelum/restfulie/wiki/ruby_tokamak
https://github.com/caelum/restfulie/wiki
...

Since the new version now uses hypertemplate, I think the wiki should be
updated as well.

## 

Reply to this email directly or view it on GitHub:
https://github.com/caelum/restfulie/issues/74

**Comment by guilhermesilveira** [comment]
Changed both files, closing. Let me know if there was something missing.
